### ISSUE TITLE
Optimization suggestions

### ISSUE THREAD

**Issue by Tamir198** [guyluz11/guyluz11#1]
Please notice those  grammar mistakes:

- *welcom* **should be**  **welcome** 

- *And here **is** links*  **should be** *And here **are** links*

- *maybe you will found script*  **should be**  *maybe you will found **a** script*

------

You can put your links more elegantly like this:

This is what you currently have:

LinkedIn - https://www.linkedin.com/in/guy-luz-7319487a/ 

You can also show this like "[LinkedIn](your link)" and you will see [LinkedIn]( https://www.linkedin.com/in/guy-luz-7319487a/)

**Comment by guyluz11** [comment]
Thanks @Tamir198 ,
Updated the README.md with your suggestions
https://github.com/guyluz11/guyluz11/commit/9b7257096477915fb38f09c8f261c00f1735184e
